/* Copyright 2026 上海如静知华信息科技有限公司 */
export const domain={
 code:'CREDITAI',systemName:'知华企业信用智能管理平台',englishName:'AI CREDIT MANAGEMENT',theme:{primary:'#52627a',dark:'#2a3445',accent:'#c68a48'},workspace:'集团财务 / 信用管理中心',fieldWorkspace:'华东区域 / 信用分析组',period:'2026-08-19 · 日内评估',liveText:'应收与外部信用数据于 10:36 更新',fieldContextLabel:'评估批次',fieldContext:'华东经销商 · 年度复评',fieldUser:'唐悦',fieldRole:'信用分析师',adminUser:'孟川',adminRole:'信用管理负责人',
 adminTitle:'企业信用风险控制中心',adminBreadcrumb:'集团财务 / 智能信用',adminSubtitle:'结合营收、应收、逾期、付款历史和外部风险，为 B2B 客户生成可解释的额度与账期建议。',exportAction:'导出信用报告',createAction:'新建评估任务',chartTitle:'信用评估完成趋势',chartSubtitle:'实际完成率 / 评估目标',chartLabels:['01日','04日','07日','10日','13日','16日','19日','22日','25日'],loadTitle:'客户组合风险负荷',loadSubtitle:'待评客户占分析团队容量',recordsTitle:'重点信用评估任务',recordsSubtitle:'按逾期、敞口和额度影响排序',issueTitle:'信用风险事件',issueSubtitle:'需要财务、销售或风险委员会确认',
 recordName:'信用任务',itemName:'客户组合',unitName:'信用团队',batchName:'评估类型',planName:'客户',doneName:'已评估',exceptionName:'高风险',unitLabel:'户',listBreadcrumb:'信用管理 / 评估任务',listSubtitle:'管理客户准入、额度、账期、定期复评和风险审批，保留每次依据。',listSummary:[['受评客户','1,268'],['待评估','86'],['高风险','24',true],['额度审批','18']],tabs:['全部','待评估','分析中','待审批','已归档'],
 fieldBreadcrumb:'信用工作台 / 华东区域',fieldTitle:'客户信用评估工作台',fieldSubtitle:'我的任务 16 项 · 高风险 4 项 · 待额度审批 6 项',fieldSecondary:'查看应收账龄',reportAction:'提交评估意见',fieldNoticeTitle:'信用数据准备完成',fieldNotice:'关键字段覆盖率 94.8%',steps:['数据准备','风险评分','额度建议','人工审批','账期执行'],documentAction:'查看信用报告',printAction:'导出审批单',resourceCardTitle:'信用数据资源',resourceValueLabel:'今日计算量',resourceHealthLabel:'数据完整度',quickSubtitle:'常用信用入口',quickActions:[['评估反馈','/shopfloor/report','风险、额度与账期建议'],['客户组合','/shopfloor/material','营收、应收和付款历史'],['数据资源','/shopfloor/resources','应收、外部信用与规则'],['风险升级','/shopfloor/andon','重大逾期与额度冻结']],
 reportDefaults:[6,1],reportTitle:'信用评估反馈',reportSubtitle:'记录风险判断、建议额度与业务依据。',reportSuccess:'信用评估意见已提交',reportPlaceholder:'填写应收、付款、经营情况和额度建议',reportFootnote:'高额授信与中高风险客户必须经过授权审批',ruleTitle:'信用额度安全门禁',ruleSubtitle:'CREDIT-AI · V1.0',rules:[['逾期 90 天','现金预付'],['高额授信','风险委员会审批'],['外部数据','校验时效'],['客户复评','至少每年一次',true]],fieldTotals:[['16','我的任务'],['4','高风险客户'],['6','待额度审批'],['94.8%','数据覆盖率']],
 adminMenus:[['/admin','home','信用控制中心'],['/admin/work-orders','order','评估任务'],['/admin/samples','box','客户组合'],['/admin/schedule','calendar','复评日历'],['/admin/methods','process','评分策略'],['/admin/reviews','quality','额度审批'],['/admin/resources','machine','信用数据'],['/admin/report','chart','风险分析']],fieldMenus:[['/shopfloor','home','信用工作台'],['/shopfloor/report','report','评估反馈'],['/shopfloor/tasks','order','我的任务'],['/shopfloor/material','box','客户组合'],['/shopfloor/resources','machine','数据状态'],['/shopfloor/andon','risk','风险升级',4]],moduleTitles:{tasks:['我的评估任务','查看优先级、敞口与到期时间'],material:['客户信用组合','查看营收、应收、逾期和付款历史'],resources:['信用数据中心','管理应收、外部信用和规则服务'],andon:['信用风险升级','提交重大逾期、异常交易和额度冻结'],samples:['客户组合台账','维护客户层级、区域和责任人'],schedule:['信用复评日历','安排年度复评和临时评估'],methods:['信用评分策略','维护风险因子、额度和账期规则'],reviews:['额度审批','记录采纳、调整和驳回意见'],report:['信用风险分析','分析逾期、敞口、损失和额度使用']},
 tagline:'让每一笔企业授信，都有数据和审批依据',storyTitle:'从客户经营与付款记录，<br/>形成透明的额度建议',storyText:'AI 负责整理风险信号，信用人员负责业务判断，风险委员会保留重大授信决策权。',pattern:[2,5,8,11,14,17,20,23,26,29,31],loginStats:[['1,268','受评客户'],['24','高风险客户'],['¥8,600万','受控敞口']],loginTitle:'企业信用风险控制中心',adminDemo:'客户 / 风险 / 额度',fieldDemo:'评估 / 依据 / 审批'}
export const records=[{no:'CR-260819-118',name:'华东经销商年度授信',code:'CUS-88621',unit:'华东信用组',group:'渠道事业部',plan:120,done:78,exception:9,due:'08-19',batch:'年度复评',status:'分析中',progress:65,priority:'关注'},{no:'CR-260819-112',name:'新客户首笔账期',code:'CUS-88576',unit:'信用管理中心',group:'商用事业部',plan:80,done:52,exception:4,due:'08-20',batch:'新客准入',status:'待评估',progress:65,priority:'正常'},{no:'CR-260819-106',name:'大额额度调整申请',code:'CUS-46218',unit:'风险审批组',group:'大客户事业部',plan:60,done:26,exception:12,due:'08-19',batch:'高额审批',status:'待审批',progress:43,priority:'紧急'},{no:'CR-260819-099',name:'稳定客户例行复评',code:'CUS-88492',unit:'华东信用组',group:'渠道事业部',plan:90,done:90,exception:1,due:'08-18',batch:'低风险',status:'已归档',progress:100,priority:'正常'}]
export const resources=[{code:'AR-01',name:'应收账款数据源',unit:'财务数据组',status:'运行中',health:99,value:'1,268',valueUnit:'户',note:'账龄于 10:20 完成同步'},{code:'BUREAU-02',name:'外部信用连接器',unit:'风险数据组',status:'运行中',health:96,value:'94.8',valueUnit:'%',note:'关键字段覆盖保持稳定'},{code:'LIMIT-03',name:'额度规则引擎',unit:'信用策略组',status:'预警',health:90,value:'18',valueUnit:'项',note:'6 项高额申请等待审批'}]
export const reviews=[{no:'RV-260819-032',title:'大额额度调整申请',type:'额度审批',detail:'建议额度 680 万 · 孟川',result:'待确认'},{no:'RV-260819-027',title:'稳定客户例行复评',type:'年度复评',detail:'风险等级 LOW · 唐悦',result:'通过'},{no:'RV-260819-018',title:'华东经销商逾期异常',type:'逾期复核',detail:'最长逾期 96 天',result:'异常'}]
export const adminMetrics=[['受评客户','1,268','覆盖 6 个事业部','blue'],['信用敞口','¥8,600万','额度使用率 68.4%','green'],['高风险客户','24','其中 9 户已逾期','orange'],['待额度审批','18','6 项超过 500 万','red']]
export const fieldMetrics=[['我的任务','16','4 项高风险','blue'],['今日已评估','32','平均 18 分钟','green'],['待额度审批','6','2 项今日到期','orange'],['数据覆盖率','94.8%','3 户缺外部数据','slate']]
export const chartActual=[52,59,66,71,76,81,85,89,92],chartTarget=[58,64,70,76,81,85,89,93,95]
export const loads=[['渠道客户',86,'待评 42 户'],['大客户',78,'待评 18 户'],['商用客户',64,'待评 16 户'],['海外客户',48,'待评 10 户']]
export const issues=[['逾期','经销客户最长逾期超过 90 天','建议暂停新增信用订单','待决策'],['敞口','大客户额度使用率升至 96%','需要补充回款计划','处理中'],['数据','3 户外部信用数据已过期','暂按保守策略评估','待更新']].map(x=>({type:x[0],title:x[1],detail:x[2],status:x[3]}))
